### PR TITLE
Security updates

### PR DESCRIPTION
**Pull request by alxberardi**

### CODE REVIEW

**Comment by AlessandroBerardi** [comment]
Travis is a bit out of whack @mnoack : https://travis-ci.org/sealink/lagomorph/jobs/105090460

**Comment by vgmaster21** [comment]
Looks like Travis needs some love.

**Comment by msmirnoff** [comment]
Make CI happy and :+1:

**Comment by AlessandroBerardi** [comment]
@msmirnoff CI seems to have problems installing gems, not at the specs level. It seems like a specific bug on Travis, which I'm trying to address, but can't reproduce locally. I might have to drop support in Travis for those Ruby versions for now.

**Pull request merged**
